apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-azure-app
  namespace: devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-azure-app
  template:
    metadata:
      labels:
        app: devops-azure-app
    spec:
      containers:
        - name: devops-azure-app
          image: REPLACE_ACR_LOGIN_SERVER/devops-azure-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
